server:
  port: 8088
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql:///ts?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  mvc:
    static-path-pattern: /upload/**
  jpa:
    hibernate:
      ddl-auto: update
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.ts.entity
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_empty
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

unLoginApi: /User/Login
